name       : font-ibm-plex
version    : 2.0.0
release    : 7
source     :
    - https://github.com/IBM/plex/archive/v2.0.0.tar.gz : 5f19741813ffdb4218253dbb0be26b56bf021b8919c42f8c6762d64e71109063
license    : OFL-1.1
component  : desktop.font
summary    : IBM Plex Typeface
description: |
    The package of IBM’s new typeface, IBM Plex in both OpenType and TrueType formats.
install    : |
    for cat in Arabic Devanagari Mono Sans Sans-Condensed Sans-Hebrew Sans-Thai-Looped Serif Thai; do
        install -D -m00644 IBM-Plex-${cat}/fonts/complete/otf/*.otf -t $installdir/usr/share/fonts/opentype/ibmplex/
        install -D -m00644 IBM-Plex-${cat}/fonts/complete/ttf/*.ttf -t $installdir/usr/share/fonts/truetype/ibmplex/
    done

    # No otf are shipped with this one
    install -D -m00644 IBM-Plex-Sans-Variable/fonts/complete/ttf/*.ttf -t $installdir/usr/share/fonts/truetype/ibmplex/
