name       : font-ibm-plex
version    : 1.2.3
release    : 5
source     :
    - https://github.com/IBM/plex/archive/v1.2.3.tar.gz : 8ab55e41861babdad99a77f955590308fc9e15426ca76db153120dd7e21b1083
license    : OFL-1.1
component  : desktop.font
summary    : IBM Plex Typeface
description: |
    The package of IBM’s new typeface, IBM Plex in both OpenType and TrueType formats.
install    : |
    for cat in Devanagari Mono Sans Sans-Condensed Sans-Hebrew Serif Thai; do
        install -D -m00644 IBM-Plex-${cat}/fonts/complete/otf/*.otf -t $installdir/usr/share/fonts/opentype/ibmplex/
        install -D -m00644 IBM-Plex-${cat}/fonts/complete/ttf/*.ttf -t $installdir/usr/share/fonts/truetype/ibmplex/
    done
