name       : font-ibm-plex
version    : 1.2.1
release    : 4
source     :
    - https://github.com/IBM/plex/archive/v1.2.1.tar.gz : e4e0c5f283da40de644321df04edc9cd65ddee0ebf998597a3039138a5a405e5
license    : OFL-1.1
component  : desktop.font
summary    : IBM Plex Typeface
description: |
    The package of IBM’s new typeface, IBM Plex in both OpenType and TrueType formats.
install    : |
    for cat in Mono Sans Sans-Condensed Serif Sans-Hebrew Thai; do
        install -D -m00644 IBM-Plex-${cat}/fonts/complete/otf/*.otf -t $installdir/usr/share/fonts/opentype/ibmplex/
        install -D -m00644 IBM-Plex-${cat}/fonts/complete/ttf/*.ttf -t $installdir/usr/share/fonts/truetype/ibmplex/
    done

