name       : font-ibm-plex
version    : 1.0.1
release    : 1
source     :
    - https://github.com/IBM/plex/archive/v1.0.1.tar.gz : 76560a0db99f494754fcbca979ed245b2bf4314d56445b749c83a3f8a481446c
license    : OFL-1.1
component  : desktop.font
summary    : IBM Plex Typeface
description: |
    The package of IBM’s new typeface, IBM Plex in both OpenType and TrueType formats.
install    : |
    for cat in Mono Sans Sans-Condensed Serif; do
        install -D -m00644 IBM-Plex-${cat}/fonts/complete/otf/*.otf -t $installdir/usr/share/fonts/opentype/ibmplex/
        install -D -m00644 IBM-Plex-${cat}/fonts/complete/ttf/*.ttf -t $installdir/usr/share/fonts/truetype/ibmplex/
    done

