name       : font-ibm-plex
version    : 1.4.1
release    : 6
source     :
    - https://github.com/IBM/plex/archive/v1.4.1.tar.gz : 4b9aa7e988856f412271964fb13eaab88fa0a890998dbb41067f85d2ba8a99bd
license    : OFL-1.1
component  : desktop.font
summary    : IBM Plex Typeface
description: |
    The package of IBM’s new typeface, IBM Plex in both OpenType and TrueType formats.
install    : |
    for cat in Arabic Devanagari Mono Sans Sans-Condensed Sans-Hebrew Serif Thai Thai-Looped; do
        install -D -m00644 IBM-Plex-${cat}/fonts/complete/otf/*.otf -t $installdir/usr/share/fonts/opentype/ibmplex/
        install -D -m00644 IBM-Plex-${cat}/fonts/complete/ttf/*.ttf -t $installdir/usr/share/fonts/truetype/ibmplex/
    done
